FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN npm config set proxy http://proxy.statestr.com:80
RUN npm config set https-proxy http://proxy.statestr.com:80
RUN npm install
COPY . .
CMD ["npm","run","start"]

